[tools]
shfmt = "latest"
stylua = "latest"
prettier = "latest"

[tasks.fmt]
description = "Format all files"
run = "shfmt -w -i 4 bin/* interceptors/python interceptors/pip && stylua hooks/ metadata.lua && prettier -w *.md"
